spring.datasource.url=jdbc:postgresql://localhost:5433/starostat_db
spring.datasource.username=catcommunist
spring.datasource.password=@Pvp25022006
spring.datasource.connection-properties=lc_messages=en_US.UTF-8